# Generated by Django 5.1.3 on 2024-11-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_servicerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_representative',
        ),
    ]
