# Generated by Django 5.1.3 on 2024-11-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_is_customer_user_is_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_representative',
            field=models.BooleanField(default=False),
        ),
    ]
