# Generated by Django 5.1.3 on 2024-11-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_user_username_alter_user_is_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='resolved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
